apiVersion: v1
kind: Secret
metadata:
  name: micewriter-engine-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MINIO_ACCESS_KEY: {{ .Values.engine.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.engine.minioSecretKey | quote }}
