apiVersion: v1
kind: Service
metadata:
  name: micewriter-k8s-injector
  namespace: micewriter-system
spec:
  selector:
    app: micewriter-k8s-injector
  ports:
    - name: https
      port: 443
      targetPort: 8443
